/**
 * Shared type definitions used across all runtime domains.
 *
 * Domain: shared
 *
 * Defines fundamental type aliases and interfaces (TokenUsage, ActionResult, etc.)
 * that are referenced by core, executor, planner, tools, telemetry, and CLI modules.
 * Keeps domain-specific files decoupled from each other by providing a common vocabulary.
 */

/**
 * Defines the operational mode of an agent, controlling how the runtime cycle
 * behaves (e.g., whether it waits for user input or runs autonomously).
 *
 * Used by: AgentState, contracts loader, cycle runner, CLI options.
 */
export type AgentType = "task_based" | "interactive" | "goal_oriented" | "autonomous";

/**
 * Primitive type identifiers for tool input parameters.
 *
 * Maps directly to the Zod schemas used for payload validation in the executor.
 * Must stay in sync with ParamTypeSchema in contracts/schemas.ts.
 */
export type ParamType = "string" | "int" | "float" | "bool" | "list" | "object";

/**
 * The three possible actions the LLM planner can return in each cycle step.
 *
 * - CHAMAR_FERRAMENTA: Execute a registered tool
 * - FINALIZAR: Declare the objective achieved
 * - PERGUNTAR_USUARIO: Ask the user for clarification
 *
 * Used by: Plan, circuit breaker validation, cycle runner action dispatch.
 */
export type ActionType = "CHAMAR_FERRAMENTA" | "FINALIZAR" | "PERGUNTAR_USUARIO";

/**
 * Quality rating assigned by the evaluator after each completed action.
 *
 * Used by: Evaluation interface, trace summary, health metrics.
 */
export type QualityRating = "completa" | "parcial" | "falha";

/**
 * Type of hook action that can be triggered during lifecycle events.
 *
 * - log: Write to the structured logger
 * - alerta: Emit a high-priority alert (e.g., for human confirmation)
 *
 * Used by: HooksContract, hook executor.
 */
export type HookAction = "log" | "alerta";

/**
 * Output format for agent final results, matching the contrato_saida.formato
 * field from the agent contract.
 *
 * Used by: AgentContract, CLI output handling.
 */
export type OutputFormat = "json" | "texto" | "relatorio";

/**
 * Tracks token consumption across prompt, completion, and total counts.
 *
 * Aggregated by the telemetry collector and reported in the post-run KPI panel.
 * Also stored in each Trace for replay analysis.
 */
export interface TokenUsage {
  /** Tokens consumed by the system + user prompt. */
  readonly prompt: number;
  /** Tokens generated by the LLM completion. */
  readonly completion: number;
  /** Sum of prompt + completion tokens. */
  readonly total: number;
}

/**
 * Zero-value constant used as initial accumulator for token usage aggregation.
 *
 * Avoids undefined checks when summing token counts across multiple LLM calls.
 */
export const EMPTY_TOKEN_USAGE: TokenUsage = {
  prompt: 0,
  completion: 0,
  total: 0,
} as const;

/**
 * Outcome of a tool execution, returned by ToolFunction implementations.
 *
 * The Portuguese field names (sucesso, dados, erro) mirror the Python runtime's
 * contract to maintain compatibility with existing agent definitions.
 *
 * Used by: ToolExecutorContext, HistoryEntry, TelemetryEvent data.
 */
export interface ActionResult {
  /** Whether the tool execution succeeded without errors. */
  readonly sucesso: boolean;
  /** Tool-specific output data (structure defined by the skill contract). */
  readonly dados: Record<string, unknown>;
  /** Error message if sucesso is false; empty string on success. */
  readonly erro: string;
  /** Token usage recorded during this specific tool call (for LLM-backed tools). */
  readonly _tokens: TokenUsage;
  /** Original input arguments passed to the tool (for audit trail). */
  readonly _entrada: Record<string, unknown>;
}

/**
 * Schema mapping parameter names to their allowed types for a skill contract.
 *
 * Used by: SkillSchema, ToolboxToolSchema, payload validation.
 */
export interface SkillParamSchema {
  /** Maps each parameter name to its ParamType (e.g., "query" -> "string"). */
  readonly [paramName: string]: ParamType;
}
